apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "instances=ci-cd-404512:us-central1:cloud-rmd-db=tcp:0.0.0.0:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        volumeMounts:
          - mountPath: /secrets/cloudsql
            name: cloudsql-instance-credentials
            readOnly: true
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: cloudsql-db-credentials

          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: cloudsql-db-credentials

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: database
                name: cloudsql-db-credentials
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "150Mi"
            cpu: "125m"
        ports:
        - containerPort: 3306
          hostPort: 3307
        securityContext:
          runAsNonRoot: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---


apiVersion: v1
kind: Service
metadata:
  name: cloudsql-services
spec:
  type: LoadBalancer
  selector:
    app: cloudsql-proxy
  ports:
  - port: 3306
    targetPort: 3306
  

            

